version: '3.8'

services:
  firebase:
    image: andreysenov/firebase-tools:latest
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "9099:9099"  # Auth
      - "9199:9199"  # Storage
      - "4000:4000"  # UI
      - "4400:4400"  # Hub
      - "4500:4500"  # Reserved
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    command: firebase emulators:start --project demo-${PROJECT_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:4000"]
      interval: 5s
      timeout: 3s
      retries: 3 