version: '3.8'

services:
  supabase-db:
    image: supabase/postgres:15.1.0.117
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./supabase/migrations:/docker-entrypoint-initdb.d/migrations
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 3

  supabase-rest:
    image: postgrest/postgrest:v11.2.0
    ports:
      - "54321:3000"
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@supabase-db:5432/postgres"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "anon"
    depends_on:
      supabase-db:
        condition: service_healthy

  core:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres
    depends_on:
      supabase-rest:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 5s
      timeout: 3s
      retries: 3 