services:
  - name: tiktoken-api
    type: web
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: docker build -t tiktoken-api --target production .
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8000
      - key: DEBUG
        value: false
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    plan: starter
    
  - name: tiktoken-web
    type: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://tiktoken-api.onrender.com
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 