version: '3.8'

services:
  # Core API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_EMULATOR: ${FIREBASE_EMULATOR}
      FIREBASE_AUTH_EMULATOR_HOST: "firebase:9099"
      FIREBASE_FIRESTORE_EMULATOR_HOST: "firebase:8080"
      AWS_ENDPOINT: http://localstack:4566
      PORT: 5000
    depends_on:
      firebase:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3

  # AI Service (Development Mock)
  ai:
    build: 
      context: ./ai
      dockerfile: Dockerfile.dev
    volumes:
      - ./ai:/app
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: /app/models/mock
      MOCK_RESPONSES: ${MOCK_SERVICES}
      PORT: 8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Firebase Emulator
  firebase:
    image: spine3/firebase-emulator
    ports:
      - "4000:4000"  # Emulator UI
      - "9099:9099"  # Auth
      - "8080:8080"  # Firestore
    volumes:
      - ./firebase.json:/opt/workspace/firebase.json:ro
    environment:
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9099 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # AWS Services Mock
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,dynamodb
      DEFAULT_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 3 