version: '3.8'

services:
  validation:
    build: .
    mem_limit: 256M
    cpus: 0.5
    environment:
      - NODE_ENV=test
      - STATE_DIR=/app/state
      - TEMP_DIR=/app/tmp
    volumes:
      - ./tests/fixtures:/app/fixtures:ro
      - ./state:/app/state
      - ./tmp:/app/tmp
    tmpfs:
      - /app/tmp:exec,mode=1777
    healthcheck:
      test: ["CMD", "node", "-e", "require('fs').accessSync('/app/fixtures')"]
      interval: 10s
      timeout: 5s
      retries: 3
