name: Set Package Visibility

on:
  workflow_dispatch:

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: Make package public
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.request('PATCH /orgs/{org}/packages/container/{package_name}/visibility', {
              org: context.repo.owner,
              package_name: 'tiktoken-core',
              visibility: 'public'
            }); 